### ISSUE TITLE
Update for MathJax 2.6

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-i18n#14]
We introduced new strings in 2.6.0 (and planning another in 2.6.1). We need to update this repository and feed things back into translatewiki.net.

**Comment by pkra** [comment]
@dpvc could you make a list of the relevant strings?

**Comment by dpvc** [comment]
I think this covers the additions for 2.6.x:

### MathMenu.js ###
```
CloseAboutDialog: "Close about MathJax dialog"
FastPreview "Fast Preview"
AssistiveMML: "Assistive MathML"
InTabOrder: "Include in Tab Order"
```

Do we want these following ones? The other renderers don't have translations, but
they are technical names and these aren't.

```
CommonHTML: "Common HTML"
PreviewHTML: "Preview HTML"
PlainSource: "Plain Source"
```

### HelpDialog.js ###
```
CloseDialog: "Close help dialog"
```

### (language).js ###
```
ErrorTips: "Debugging tips: use %1, inspect %2 in the browser console"
```

There are also the strings for the accessibility menus.  Because these are not part of the core, I'm not sure how best to handle them.  The easiest thing would be to add them to the MathMenu localization files, but because they are in the third-party repository, technically, they should have their own third-party localization files; but we don't really have a good mechanism of handling that when the extension modifies an existing localized component (like the menu).  Since we are including the menus in the combined configuration files, it would be good to have the localizations available.

How would you like proceed?

**Comment by pkra** [comment]
> How would you like proceed?

I'd love to pass that on 😄  cc @siebrand @Nikerabbit -- do you have a preferred way of adding new strings? (E.g., here or better at translatewiki.net?)

**Comment by Nikerabbit** [comment]
Yes, they must be in the English localisation files. Don't forget to add message documentation in qqq either, it's very useful to translators.

**Comment by pkra** [comment]
> Yes, they must be in the English localisation files. Don't forget to add message documentation in qqq either, it's very useful to translators.

Just to double check: You want us to change the files in this repository, correct?

**Comment by Nikerabbit** [comment]
Yes this is the repo we pull and push changes.

**Comment by pkra** [comment]
Thanks, @Nikerabbit!

**Comment by nemobis** [comment]
Was this still not done? At any rate, please make sure to remove any string which is unused, in order not to waste translator work.

**Comment by pkra** [comment]
> Was this still not done?

I'm afraid so.

> please make sure to remove any string which is unused

There are no unused strings at this time.

**Comment by pkra** [comment]
@Nikerabbit @siebrand  is there anything else you need from our end after the #19?

**Comment by Nikerabbit** [comment]
These are already available for translations, and being translated: https://translatewiki.net/w/i.php?title=Special:Translations&message=MathJax%3AHelpdialog-CloseDialog%2Ffi

**Comment by pkra** [comment]
Thanks, @Nikerabbit -- awesome!
